### ISSUE TITLE
Incompatible with ruby 2.4.0+

### ISSUE THREAD

**Issue by jasonkarns** [bjeanes/optparse-subcommand#4]
2.4.0 adds the keyword arg `into` as second param to `order`, `parse` and `permute` (and the `!` variants).

Attempting to use optparse/subcommand with the extra parameter throws an ArgumentError:
```
`parse!': wrong number of arguments (2 for 0..1) (ArgumentError)
```

**Comment by bjeanes** [comment]
Thanks @jasonkarns!
